export interface IAppliedLoan {
    email: string,
    gender: string,
    name: string,
    password: string,
    role: string,
    customerPicture: string,
    logo: string,
    title: string,
    loanAmount: string,
    appliedAmount: number,
    interestRates: string,
    designatedRate: number,
    Mincreditscore: number,
    TermLength: number,
    ProcessingFee: number,
    currentemployer: string,
    designation: string,
    salary: number,
    approved: boolean,
    rejected: boolean,
    pending: boolean,
    dateApplied: Date,
    id: number
}
